export type HackathonStatus = "upcoming" | "ongoing" | "past";
export type LocationType = "virtual" | "in-person" | "hybrid";

export interface Hackathon {
  id: number;
  name: string;
  organizer: string;
  logo: string;
  description: string;
  prizePool: string;
  startDate: string;
  endDate: string;
  location: string;
  locationType: LocationType;
  website: string;
  tags: string[];
  tracks: string[];
  eligibility: string;
  status: HackathonStatus;
  ecosystem: string;
  highlights: string[];
}

export const hackathons: Hackathon[] = [
  {
    id: 1,
    name: "ETHGlobal Istanbul",
    organizer: "ETHGlobal",
    logo: "https://avatars.githubusercontent.com/u/35137725",
    description:
      "ETHGlobal Istanbul brings together thousands of developers, designers, and builders at the crossroads of Europe and Asia. Over a weekend of intense building, participants create projects spanning DeFi, infrastructure, social, and more, all powered by Ethereum and its ecosystem.",
    prizePool: "$500,000+",
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    location: "Istanbul, Turkey",
    locationType: "hybrid",
    website: "https://ethglobal.com/events/istanbul",
    tags: ["Ethereum", "DeFi", "Infrastructure", "Social"],
    tracks: [
      "DeFi and Payments",
      "Developer Tooling",
      "Social and Identity",
      "Public Goods",
      "L2 and Scalability",
    ],
    eligibility:
      "Open to all developers, designers, and builders worldwide. Teams of up to 4 members.",
    status: "upcoming",
    ecosystem: "Ethereum",
    highlights: [
      "$500K+ in prizes from sponsors",
      "Mentorship from top Ethereum core developers",
      "Hybrid format with in-person and virtual tracks",
    ],
  },
  {
    id: 2,
    name: "ETHGlobal San Francisco",
    organizer: "ETHGlobal",
    logo: "https://avatars.githubusercontent.com/u/35137725",
    description:
      "One of the flagship ETHGlobal events, held in the heart of Silicon Valley. Builders from around the world gather to hack on Ethereum projects, attend workshops, and compete for substantial prizes across multiple sponsor tracks.",
    prizePool: "$600,000+",
    startDate: "2026-10-10",
    endDate: "2026-10-12",
    location: "San Francisco, USA",
    locationType: "hybrid",
    website: "https://ethglobal.com/events/sanfrancisco",
    tags: ["Ethereum", "AI", "DeFi", "Wallets"],
    tracks: [
      "AI and Blockchain",
      "DeFi Innovations",
      "Account Abstraction",
      "Privacy and Security",
    ],
    eligibility:
      "Open to all skill levels. Individual participants and teams of up to 4 welcome.",
    status: "upcoming",
    ecosystem: "Ethereum",
    highlights: [
      "Located in the global tech capital",
      "Direct access to top VC and protocol teams",
      "Workshops led by Ethereum Foundation researchers",
    ],
  },
  {
    id: 3,
    name: "ETHGlobal Bangkok",
    organizer: "ETHGlobal",
    logo: "https://avatars.githubusercontent.com/u/35137725",
    description:
      "ETHGlobal Bangkok takes place during the annual Devcon week, making it one of the most anticipated Ethereum hackathons of the year. Thousands of builders converge to prototype, ship, and demo cutting-edge Ethereum applications.",
    prizePool: "$750,000+",
    startDate: "2026-11-14",
    endDate: "2026-11-16",
    location: "Bangkok, Thailand",
    locationType: "hybrid",
    website: "https://ethglobal.com/events/bangkok",
    tags: ["Ethereum", "Devcon", "ZK", "MEV"],
    tracks: [
      "Zero Knowledge Proofs",
      "MEV and Sequencing",
      "Cross-chain Interoperability",
      "Consumer Applications",
      "Public Goods",
    ],
    eligibility:
      "Open to all builders globally. No prior hackathon experience required. Teams of 1-4.",
    status: "upcoming",
    ecosystem: "Ethereum",
    highlights: [
      "Co-located with Devcon for maximum networking",
      "$750K+ across sponsor and main prizes",
      "Access to the largest Ethereum developer gathering",
    ],
  },
  {
    id: 4,
    name: "ETHGlobal New York",
    organizer: "ETHGlobal",
    logo: "https://avatars.githubusercontent.com/u/35137725",
    description:
      "ETHGlobal New York unites developers and entrepreneurs in one of the world's financial capitals. The event emphasizes real-world applications of Ethereum, from DeFi to tokenized assets, with strong participation from institutional partners.",
    prizePool: "$500,000+",
    startDate: "2025-09-26",
    endDate: "2025-09-28",
    location: "New York, USA",
    locationType: "hybrid",
    website: "https://ethglobal.com/events/newyork",
    tags: ["Ethereum", "RWA", "DeFi", "Identity"],
    tracks: [
      "Real World Assets",
      "Decentralized Identity",
      "DeFi and Payments",
      "Developer Experience",
    ],
    eligibility:
      "Open to developers and designers of all backgrounds. Teams of up to 4.",
    status: "past",
    ecosystem: "Ethereum",
    highlights: [
      "Strong institutional and enterprise partner presence",
      "RWA-focused track attracted major finance teams",
      "Over 2,000 participants across hybrid format",
    ],
  },
  {
    id: 5,
    name: "Solana Hyperdrive",
    organizer: "Solana Foundation",
    logo: "https://cryptologos.cc/logos/solana-sol-logo.svg",
    description:
      "Solana Hyperdrive is the Solana ecosystem's flagship global online hackathon, attracting thousands of submissions from builders worldwide. With a $1M prize pool, it is one of the largest crypto hackathons by total rewards, covering DeFi, infrastructure, mobile, and DAOs.",
    prizePool: "$1,000,000",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://solana.com/hyperdrive",
    tags: ["Solana", "DeFi", "Mobile", "DAO"],
    tracks: [
      "DeFi and Payments",
      "Infrastructure and Tooling",
      "Mobile Consumer",
      "DAOs and Network States",
      "Gaming and Entertainment",
    ],
    eligibility:
      "Open to developers worldwide. Solo builders and teams of any size. Must deploy on Solana.",
    status: "upcoming",
    ecosystem: "Solana",
    highlights: [
      "$1M total prize pool across all tracks",
      "Past editions received 900+ submissions",
      "Winners receive follow-on support from Solana Foundation",
    ],
  },
  {
    id: 6,
    name: "Solana Grizzlython",
    organizer: "Solana Foundation",
    logo: "https://cryptologos.cc/logos/solana-sol-logo.svg",
    description:
      "Grizzlython challenged developers to build the next wave of Solana applications across five categories. The hackathon attracted hundreds of projects exploring DeFi, payments, mobile, and DAOs on the high-performance Solana blockchain.",
    prizePool: "$500,000",
    startDate: "2025-02-02",
    endDate: "2025-03-14",
    location: "Virtual",
    locationType: "virtual",
    website: "https://solana.com/grizzlython",
    tags: ["Solana", "Payments", "DAOs", "Infrastructure"],
    tracks: [
      "Payments",
      "DAOs and Network States",
      "Data and Analytics",
      "Mobile Consumer",
      "Infrastructure",
    ],
    eligibility:
      "Open to all developers. Projects must use Solana. Individual and team participation allowed.",
    status: "past",
    ecosystem: "Solana",
    highlights: [
      "$500K distributed across category winners",
      "Over 800 project submissions",
      "Strong emphasis on real-world payment use cases",
    ],
  },
  {
    id: 7,
    name: "Polygon DevX Global Hackathon",
    organizer: "Polygon Labs",
    logo: "https://cryptologos.cc/logos/polygon-matic-logo.svg",
    description:
      "Polygon DevX Global is a virtual hackathon focused on accelerating builder adoption across the Polygon ecosystem. Participants build dApps leveraging Polygon PoS, zkEVM, and CDK, with mentorship and bounties from leading Web3 protocols.",
    prizePool: "$250,000",
    startDate: "2026-04-15",
    endDate: "2026-05-30",
    location: "Virtual",
    locationType: "virtual",
    website: "https://polygon.technology/hackathon",
    tags: ["Polygon", "zkEVM", "CDK", "L2"],
    tracks: [
      "DeFi on zkEVM",
      "Gaming and NFTs",
      "Enterprise and RWA",
      "Developer Tooling",
      "Social and Identity",
    ],
    eligibility:
      "Open to all developers. Projects must deploy on Polygon. Teams of up to 5 members.",
    status: "upcoming",
    ecosystem: "Polygon",
    highlights: [
      "Focus on zkEVM and CDK adoption",
      "Mentorship from Polygon core engineers",
      "Top teams invited to Polygon accelerator",
    ],
  },
  {
    id: 8,
    name: "Chainlink Constellation",
    organizer: "Chainlink Labs",
    logo: "https://cryptologos.cc/logos/chainlink-link-logo.svg",
    description:
      "Constellation is Chainlink's premier hackathon empowering developers to build smart contracts connected to real-world data and off-chain computation. The event covers CCIP, Functions, Automation, and VRF, driving multi-chain development.",
    prizePool: "$400,000+",
    startDate: "2026-08-01",
    endDate: "2026-09-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://chain.link/hackathon",
    tags: ["Chainlink", "Oracles", "CCIP", "Multi-chain"],
    tracks: [
      "Cross-Chain with CCIP",
      "Chainlink Functions",
      "Automation and VRF",
      "DeFi Protocols",
    ],
    eligibility:
      "Open to all developers. No prior blockchain experience required. Teams of up to 5.",
    status: "upcoming",
    ecosystem: "Multi-chain",
    highlights: [
      "$400K+ in prizes including sponsor bounties",
      "Beginner-friendly with guided workshops",
      "Previous editions attracted 16,000+ registrants",
    ],
  },
  {
    id: 9,
    name: "Encode Club Hackathon",
    organizer: "Encode Club",
    logo: "https://avatars.githubusercontent.com/u/65674820",
    description:
      "Encode Club runs multi-week hackathons in partnership with leading blockchain protocols. Participants learn through bootcamps, build projects over several weeks, and receive feedback from expert judges. Known for strong educational components alongside building.",
    prizePool: "$200,000",
    startDate: "2026-03-01",
    endDate: "2026-03-28",
    location: "Virtual",
    locationType: "virtual",
    website: "https://www.encode.club/hackathons",
    tags: ["Education", "Multi-chain", "Bootcamp", "ZK"],
    tracks: [
      "Zero Knowledge",
      "DeFi Primitives",
      "AI and Blockchain",
      "Public Goods",
    ],
    eligibility:
      "Open to developers at all levels. Bootcamp included for beginners. Teams of 2-5 members.",
    status: "ongoing",
    ecosystem: "Multi-chain",
    highlights: [
      "Includes a free pre-hackathon bootcamp",
      "Multi-week format for deeper project development",
      "Strong alumni network of 50,000+ builders",
    ],
  },
  {
    id: 10,
    name: "ETHIndia",
    organizer: "ETHGlobal",
    logo: "https://avatars.githubusercontent.com/u/35137725",
    description:
      "ETHIndia is the largest Ethereum hackathon in Asia, held in Bangalore. It draws thousands of developers from across India and Southeast Asia for a weekend of building, learning, and shipping Ethereum-based projects with world-class mentorship.",
    prizePool: "$500,000+",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
    location: "Bangalore, India",
    locationType: "in-person",
    website: "https://ethindia.co",
    tags: ["Ethereum", "India", "DeFi", "Public Goods"],
    tracks: [
      "DeFi and Payments",
      "Social and Creator Economy",
      "Infrastructure",
      "Public Goods",
      "AI on Ethereum",
    ],
    eligibility:
      "Open to all developers. Must attend in person in Bangalore. Teams of up to 4.",
    status: "upcoming",
    ecosystem: "Ethereum",
    highlights: [
      "Largest Ethereum hackathon in Asia",
      "3,000+ in-person attendees",
      "Strong focus on India's developer community",
    ],
  },
  {
    id: 11,
    name: "Hackathon by Arbitrum",
    organizer: "Arbitrum Foundation",
    logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg",
    description:
      "The Arbitrum hackathon invites developers to build on one of Ethereum's leading Layer 2 networks. Projects span DeFi, gaming, social, and developer tooling, with a focus on leveraging Arbitrum Stylus and Orbit chains for novel use cases.",
    prizePool: "$300,000",
    startDate: "2026-05-01",
    endDate: "2026-06-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://arbitrum.foundation/hackathon",
    tags: ["Arbitrum", "L2", "Stylus", "Orbit"],
    tracks: [
      "DeFi on Arbitrum",
      "Stylus Smart Contracts",
      "Orbit Chain Applications",
      "Gaming and Social",
    ],
    eligibility:
      "Open globally to developers of all experience levels. Must build on Arbitrum. Teams of 1-5.",
    status: "upcoming",
    ecosystem: "Arbitrum",
    highlights: [
      "Focus on Stylus multi-language smart contracts",
      "Orbit chain grants for winning teams",
      "Direct mentorship from Offchain Labs engineers",
    ],
  },
  {
    id: 12,
    name: "Base Onchain Summer Buildathon",
    organizer: "Coinbase / Base",
    logo: "https://avatars.githubusercontent.com/u/108554348",
    description:
      "The Onchain Summer Buildathon is Base's flagship hackathon encouraging developers to bring the next billion users onchain. It focuses on consumer-friendly applications, onchain commerce, and social experiences built on Base.",
    prizePool: "$200,000",
    startDate: "2026-06-15",
    endDate: "2026-07-31",
    location: "Virtual",
    locationType: "virtual",
    website: "https://base.org/buildathon",
    tags: ["Base", "Onchain", "Consumer", "Commerce"],
    tracks: [
      "Onchain Commerce",
      "Social and Creator Tools",
      "DeFi for Everyone",
      "Onchain Gaming",
    ],
    eligibility:
      "Open to all builders. Must deploy on Base. Individual or team participation welcome.",
    status: "upcoming",
    ecosystem: "Base",
    highlights: [
      "Emphasis on consumer-grade UX",
      "Top teams featured in Base ecosystem spotlight",
      "Follow-on funding through Base Ecosystem Fund",
    ],
  },
  {
    id: 13,
    name: "Sui Overflow",
    organizer: "Sui Foundation",
    logo: "https://cdn.prod.website-files.com/6425f546844727ce5fb9e5ab/659a55a32fcb71d65908adc3_sui-mark.svg",
    description:
      "Sui Overflow is the Sui ecosystem's global hackathon, challenging developers to push the boundaries of the Move programming language and Sui's object-centric model. The event covers DeFi, gaming, infrastructure, and NFT applications.",
    prizePool: "$350,000",
    startDate: "2026-03-03",
    endDate: "2026-04-04",
    location: "Virtual",
    locationType: "virtual",
    website: "https://sui.io/overflow",
    tags: ["Sui", "Move", "DeFi", "Gaming"],
    tracks: [
      "DeFi and Lending",
      "Gaming and NFTs",
      "Infra and Developer Tools",
      "Consumer Applications",
    ],
    eligibility:
      "Open to all developers. Familiarity with Move language recommended but not required. Teams of 1-5.",
    status: "ongoing",
    ecosystem: "Sui",
    highlights: [
      "$350K across track prizes and sponsor bounties",
      "Move language workshops for newcomers",
      "Winning projects eligible for Sui Foundation grants",
    ],
  },
  {
    id: 14,
    name: "Aptos Code Collision",
    organizer: "Aptos Foundation",
    logo: "https://cryptologos.cc/logos/aptos-apt-logo.svg",
    description:
      "Code Collision invites developers to build on the Aptos blockchain using the Move programming language. The hackathon targets both seasoned blockchain developers and newcomers, offering workshops, documentation sprints, and live coding sessions.",
    prizePool: "$250,000",
    startDate: "2026-07-01",
    endDate: "2026-08-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://aptosfoundation.org/hackathon",
    tags: ["Aptos", "Move", "Payments", "NFTs"],
    tracks: [
      "Move Smart Contracts",
      "DeFi Protocols",
      "Payments and Commerce",
      "NFTs and Digital Assets",
    ],
    eligibility:
      "Open to all developers globally. Move bootcamp included for beginners. Teams of up to 5.",
    status: "upcoming",
    ecosystem: "Aptos",
    highlights: [
      "Move bootcamp for first-time Aptos developers",
      "Google Cloud credits for all participants",
      "Top projects receive Aptos Foundation grant offers",
    ],
  },
  {
    id: 15,
    name: "Near Horizon Hackathon",
    organizer: "NEAR Foundation",
    logo: "https://cryptologos.cc/logos/near-protocol-near-logo.svg",
    description:
      "The Near Horizon Hackathon connects builders with the NEAR ecosystem, focusing on chain abstraction, AI integration, and user-friendly dApps. Participants leverage NEAR's account model and sharded architecture to build scalable applications.",
    prizePool: "$300,000",
    startDate: "2026-02-15",
    endDate: "2026-03-31",
    location: "Virtual",
    locationType: "virtual",
    website: "https://near.org/hackathon",
    tags: ["NEAR", "Chain Abstraction", "AI", "dApps"],
    tracks: [
      "Chain Abstraction",
      "AI and Blockchain",
      "DeFi on NEAR",
      "Social and Community",
      "Infrastructure",
    ],
    eligibility:
      "Open to all builders. NEAR development experience not required. Teams and solo participants welcome.",
    status: "ongoing",
    ecosystem: "NEAR",
    highlights: [
      "Focus on chain abstraction technology",
      "AI integration track attracted strong submissions",
      "Winners onboarded into NEAR Horizon accelerator",
    ],
  },
  {
    id: 16,
    name: "TON Hack",
    organizer: "TON Foundation",
    logo: "https://cryptologos.cc/logos/toncoin-ton-logo.svg",
    description:
      "TON Hack brings together developers building on The Open Network, the blockchain integrated with Telegram. The hackathon focuses on Telegram Mini Apps, bots, DeFi, and GameFi, leveraging TON's massive user base through Telegram.",
    prizePool: "$500,000",
    startDate: "2026-03-05",
    endDate: "2026-04-10",
    location: "Virtual",
    locationType: "virtual",
    website: "https://hack.ton.org",
    tags: ["TON", "Telegram", "Mini Apps", "GameFi"],
    tracks: [
      "Telegram Mini Apps",
      "DeFi and DEX",
      "GameFi and Entertainment",
      "Social and Messaging",
    ],
    eligibility:
      "Open to all developers worldwide. Telegram bot and TON SDK experience helpful but not required. Teams of up to 5.",
    status: "ongoing",
    ecosystem: "TON",
    highlights: [
      "Access to Telegram's 900M+ user distribution channel",
      "$500K prize pool across tracks",
      "Winning Mini Apps featured in Telegram discovery",
    ],
  },
  {
    id: 17,
    name: "Polkadot Global Series",
    organizer: "Web3 Foundation",
    logo: "https://cryptologos.cc/logos/polkadot-new-dot-logo.svg",
    description:
      "The Polkadot Global Series is a multi-city hackathon bringing together developers building on Polkadot, parachains, and the JAM protocol. It includes both in-person events at key Web3 conferences and a virtual track for global participation.",
    prizePool: "$350,000",
    startDate: "2025-05-01",
    endDate: "2025-06-30",
    location: "Berlin, Germany + Virtual",
    locationType: "hybrid",
    website: "https://polkadot.network/hackathon",
    tags: ["Polkadot", "Substrate", "Parachains", "JAM"],
    tracks: [
      "Parachain Development",
      "Cross-Chain Messaging (XCM)",
      "DeFi on Polkadot",
      "JAM Protocol",
      "Ink! Smart Contracts",
    ],
    eligibility:
      "Open to all developers. In-person events in Berlin; virtual participation available globally. Teams of 2-5.",
    status: "past",
    ecosystem: "Polkadot",
    highlights: [
      "Multi-city format with Berlin as flagship",
      "JAM protocol track attracted core contributors",
      "Substrate builders received Web3 Foundation grant offers",
    ],
  },
  {
    id: 18,
    name: "Avalanche Summit Hackathon",
    organizer: "Avalanche Foundation",
    logo: "https://cryptologos.cc/logos/avalanche-avax-logo.svg",
    description:
      "The Avalanche Summit Hackathon runs alongside the Avalanche Summit conference, combining an in-person hacking experience with virtual participation. Builders create projects using Subnets, HyperSDK, and the broader Avalanche C-Chain ecosystem.",
    prizePool: "$250,000",
    startDate: "2025-11-10",
    endDate: "2025-11-24",
    location: "London, UK + Virtual",
    locationType: "hybrid",
    website: "https://avalanchesummit.com/hackathon",
    tags: ["Avalanche", "Subnets", "HyperSDK", "DeFi"],
    tracks: [
      "Subnet Innovation",
      "DeFi and Lending",
      "Gaming on Avalanche",
      "Enterprise Solutions",
    ],
    eligibility:
      "Open to all developers. In-person track at Avalanche Summit in London. Virtual submissions accepted globally.",
    status: "past",
    ecosystem: "Avalanche",
    highlights: [
      "Co-located with Avalanche Summit conference",
      "Subnet-focused track drew enterprise builders",
      "Winning teams invited to Blizzard Fund pipeline",
    ],
  },
  {
    id: 19,
    name: "BNB Chain Innovation Hackathon",
    organizer: "BNB Chain",
    logo: "https://cryptologos.cc/logos/bnb-bnb-logo.svg",
    description:
      "BNB Chain's global hackathon targets builders creating the next generation of decentralized applications on BNB Smart Chain and opBNB. The event supports DeFi, GameFi, AI integration, and SocialFi, with a strong emphasis on user adoption.",
    prizePool: "$300,000",
    startDate: "2025-07-01",
    endDate: "2025-08-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://www.bnbchain.org/hackathon",
    tags: ["BNB Chain", "opBNB", "DeFi", "AI"],
    tracks: [
      "DeFi and Yield",
      "GameFi and Metaverse",
      "AI-Powered dApps",
      "SocialFi",
      "Infrastructure and Tooling",
    ],
    eligibility:
      "Open to developers and teams worldwide. Must deploy on BNB Smart Chain or opBNB. Teams of up to 5.",
    status: "past",
    ecosystem: "BNB Chain",
    highlights: [
      "$300K in prizes plus BNB Chain Builder Grants",
      "Winners fast-tracked for BNB Incubation Alliance",
      "Access to BNB Chain's 1M+ daily active users",
    ],
  },
  {
    id: 20,
    name: "Filecoin Data Economy Hack",
    organizer: "Filecoin Foundation",
    logo: "https://cryptologos.cc/logos/filecoin-fil-logo.svg",
    description:
      "The Data Economy Hack challenges builders to create applications that leverage decentralized storage through Filecoin and IPFS. Projects range from data marketplaces and archival tools to compute-over-data solutions and verifiable storage proofs.",
    prizePool: "$150,000",
    startDate: "2025-04-15",
    endDate: "2025-05-31",
    location: "Virtual",
    locationType: "virtual",
    website: "https://fil.org/hackathon",
    tags: ["Filecoin", "IPFS", "Storage", "Data"],
    tracks: [
      "Decentralized Storage Apps",
      "Data DAOs",
      "Compute Over Data",
      "IPFS Tooling",
    ],
    eligibility:
      "Open to all developers. Must use Filecoin or IPFS in the project. Individual and team submissions accepted.",
    status: "past",
    ecosystem: "Filecoin",
    highlights: [
      "Focus on decentralized data infrastructure",
      "Data DAO track produced several funded startups",
      "ProPGF grants awarded to outstanding open-source projects",
    ],
  },
  {
    id: 21,
    name: "StarkHack",
    organizer: "Starknet Foundation",
    logo: "https://www.starknet.io/wp-content/uploads/2024/01/Symbol.svg",
    description:
      "StarkHack is Starknet's premier hackathon exploring the frontiers of zero-knowledge rollup technology. Developers build using Cairo, Starknet's native smart contract language, to create scalable and private applications with cryptographic guarantees.",
    prizePool: "$200,000",
    startDate: "2026-03-08",
    endDate: "2026-04-05",
    location: "Virtual",
    locationType: "virtual",
    website: "https://www.starknet.io/starkhack",
    tags: ["Starknet", "Cairo", "ZK", "L2"],
    tracks: [
      "DeFi on Starknet",
      "Cairo Smart Contracts",
      "Gaming and Autonomous Worlds",
      "Infrastructure and Tooling",
    ],
    eligibility:
      "Open to all developers globally. Cairo workshops available for newcomers. Teams of 1-5 members.",
    status: "ongoing",
    ecosystem: "Starknet",
    highlights: [
      "Cairo language workshops and documentation sprints",
      "ZK proving track attracted cryptography researchers",
      "Winners eligible for Starknet Seed Grants",
    ],
  },
  {
    id: 22,
    name: "ICP Chain Fusion Hackathon",
    organizer: "DFINITY Foundation",
    logo: "https://cryptologos.cc/logos/internet-computer-icp-logo.svg",
    description:
      "The Chain Fusion Hackathon showcases the Internet Computer's ability to integrate with Bitcoin, Ethereum, and other chains natively. Builders create multi-chain applications using ICP's unique canister smart contracts and threshold cryptography.",
    prizePool: "$250,000",
    startDate: "2026-04-01",
    endDate: "2026-05-15",
    location: "Virtual",
    locationType: "virtual",
    website: "https://dfinity.org/hackathon",
    tags: ["ICP", "Chain Fusion", "Bitcoin", "Multi-chain"],
    tracks: [
      "Bitcoin Integration",
      "Ethereum Bridge",
      "AI on Chain",
      "Decentralized Web Hosting",
      "DAO Tooling",
    ],
    eligibility:
      "Open to developers of all levels. Motoko and Rust SDKs available. Teams of up to 5 members.",
    status: "upcoming",
    ecosystem: "Internet Computer",
    highlights: [
      "Native Bitcoin and Ethereum integration demos",
      "On-chain AI computation track",
      "DFINITY developer grants for winning teams",
    ],
  },
  {
    id: 23,
    name: "Cosmos HackAtom",
    organizer: "Interchain Foundation",
    logo: "https://cryptologos.cc/logos/cosmos-atom-logo.svg",
    description:
      "HackAtom is the Cosmos ecosystem's flagship hackathon, bringing together builders working on sovereign app-chains, IBC interoperability, and CosmWasm smart contracts. The hybrid format includes in-person events at Cosmoverse and a global virtual track.",
    prizePool: "$200,000",
    startDate: "2025-08-01",
    endDate: "2025-09-15",
    location: "Dubai, UAE + Virtual",
    locationType: "hybrid",
    website: "https://hackatom.org",
    tags: ["Cosmos", "IBC", "CosmWasm", "App-chains"],
    tracks: [
      "IBC Interoperability",
      "CosmWasm dApps",
      "Cosmos SDK Modules",
      "DeFi and MEV",
    ],
    eligibility:
      "Open to all developers. In-person component at Cosmoverse in Dubai. Virtual track available globally. Teams of 2-5.",
    status: "past",
    ecosystem: "Cosmos",
    highlights: [
      "IBC track produced cross-chain innovations",
      "Co-located with Cosmoverse conference",
      "Top teams received ATOM Accelerator DAO support",
    ],
  },
  {
    id: 24,
    name: "The Graph Data Hack",
    organizer: "The Graph Foundation",
    logo: "https://cryptologos.cc/logos/the-graph-grt-logo.svg",
    description:
      "The Graph Data Hack challenges developers to build powerful data-driven dApps using subgraphs and The Graph's indexing protocol. The hackathon emphasizes data accessibility, analytics dashboards, and AI-powered data applications across multiple chains.",
    prizePool: "$150,000",
    startDate: "2025-06-10",
    endDate: "2025-07-20",
    location: "Virtual",
    locationType: "virtual",
    website: "https://thegraph.com/hackathon",
    tags: ["The Graph", "Subgraphs", "Data", "Indexing"],
    tracks: [
      "Subgraph Development",
      "Data Analytics Dashboards",
      "AI and Data Services",
      "Cross-Chain Indexing",
    ],
    eligibility:
      "Open to all developers. GraphQL and subgraph experience helpful but not required. Teams of 1-5.",
    status: "past",
    ecosystem: "Multi-chain",
    highlights: [
      "Workshops on subgraph creation from scratch",
      "AI and data services track for emerging use cases",
      "AdvocatesDAO community grants for standout projects",
    ],
  },
  {
    id: 25,
    name: "Gitcoin GG Rounds Hackathon",
    organizer: "Gitcoin",
    logo: "https://cryptologos.cc/logos/gitcoin-gtc-logo.svg",
    description:
      "Gitcoin's hackathon runs alongside its Grants Rounds, combining competitive building with quadratic funding. Developers ship open-source public goods, compete for prizes, and simultaneously receive community donations amplified by matching pools.",
    prizePool: "$175,000",
    startDate: "2026-05-15",
    endDate: "2026-06-30",
    location: "Virtual",
    locationType: "virtual",
    website: "https://gitcoin.co/hackathon",
    tags: ["Gitcoin", "Public Goods", "Open Source", "QF"],
    tracks: [
      "Public Goods Infrastructure",
      "Developer Tooling",
      "Education and Onboarding",
      "Climate and ReFi",
      "Identity and Reputation",
    ],
    eligibility:
      "Open to all developers and teams. Projects must be open source. Individual and team participation allowed.",
    status: "upcoming",
    ecosystem: "Multi-chain",
    highlights: [
      "Quadratic funding matching on top of prizes",
      "Projects eligible for ongoing Gitcoin Grants support",
      "100% open-source requirement builds lasting public goods",
    ],
  },
];

export const HACKATHON_ECOSYSTEMS: string[] = [
  ...new Set(hackathons.map((h) => h.ecosystem)),
].sort();
